#!/usr/bin/env bash
# scripts/sbom-gen-fixtures.sh
#
# Regenerates the positive SBOM fixture under
# tests/fixtures/sbom/valid.json using the tool version pinned in
# .github/workflows/sbom.yml. Run this when bumping
# CARGO_CYCLONEDX_VERSION so the self-test exercises a real SBOM
# from the new version rather than a stale snapshot.
#
# The invalid-*.json fixtures are hand-crafted mutations of
# valid.json; they are NOT regenerated by this script because
# each one is a targeted shape violation for a specific assertion.
#
# Usage:
#   bash scripts/sbom-gen-fixtures.sh
#
# Requires: bash, cargo, cargo-cyclonedx (matching the pinned
# version), jq, and SOURCE_DATE_EPOCH support.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

# Pull the pinned version out of the workflow so this script has
# one source of truth. A version-skew between script and workflow
# would regenerate fixtures from the wrong tool.
#
# An explicit CARGO_CYCLONEDX_VERSION env var overrides the
# workflow (useful when the workflow file is not yet in the tree
# — e.g. the initial commit that introduces this script).
workflow=".github/workflows/sbom.yml"
if [ -n "${CARGO_CYCLONEDX_VERSION:-}" ]; then
    pinned_version="$CARGO_CYCLONEDX_VERSION"
elif [ -f "$workflow" ]; then
    pinned_version="$(
        awk -F'"' '/CARGO_CYCLONEDX_VERSION:/ {print $2; exit}' "$workflow"
    )"
    if [ -z "$pinned_version" ]; then
        echo "error: could not parse CARGO_CYCLONEDX_VERSION from $workflow" >&2
        exit 2
    fi
else
    echo "error: no CARGO_CYCLONEDX_VERSION env var and no $workflow to parse" >&2
    exit 2
fi

command -v cargo-cyclonedx >/dev/null 2>&1 || {
    echo "error: cargo-cyclonedx not on PATH" >&2
    echo "hint:  cargo install --locked cargo-cyclonedx --version $pinned_version" >&2
    exit 2
}

installed_version="$(cargo cyclonedx --version | awk '{print $NF}')"
if [ "$installed_version" != "$pinned_version" ]; then
    printf 'error: installed cargo-cyclonedx is %s; pinned is %s\n' \
        "$installed_version" "$pinned_version" >&2
    echo "bump the pin in $workflow OR reinstall the pinned version" >&2
    exit 2
fi

command -v jq >/dev/null 2>&1 || { echo "error: jq required" >&2; exit 2; }

fixture_dir="$repo_root/tests/fixtures/sbom"
mkdir -p "$fixture_dir"

# Use mango-proto as the source fixture: it has the richest shape
# (components, dependencies, purls, hashes, licenses) so the
# validator exercises every assertion. `mango` itself currently
# has zero components.
target_crate="mango-proto"
manifest="$repo_root/crates/$target_crate/Cargo.toml"
if [ ! -f "$manifest" ]; then
    echo "error: manifest not found for $target_crate ($manifest)" >&2
    exit 2
fi

scratch="$(mktemp -d)"
trap 'rm -rf "$scratch"' EXIT

# SOURCE_DATE_EPOCH=1 freezes metadata.timestamp and zeroes
# serialNumber so the fixture is byte-stable across regenerations.
SOURCE_DATE_EPOCH=1 cargo cyclonedx \
    --manifest-path "$manifest" \
    --format json \
    --spec-version 1.5 \
    --no-build-deps \
    >"$scratch/cyclonedx.log" 2>&1 \
|| {
    echo "error: cargo cyclonedx failed" >&2
    cat "$scratch/cyclonedx.log" >&2
    exit 3
}

emitted="$repo_root/crates/$target_crate/$target_crate.cdx.json"
if [ ! -f "$emitted" ]; then
    echo "error: cargo cyclonedx did not produce $emitted" >&2
    echo "hint:  check the --manifest-path flag and tool output:" >&2
    cat "$scratch/cyclonedx.log" >&2
    exit 3
fi

# Move the freshly-generated SBOM into the fixtures directory.
# `jq .` normalizes whitespace so git diffs on the fixture are
# about real shape changes, not tool formatting drift.
jq . "$emitted" > "$fixture_dir/valid.json"

# Clean up the generator's in-tree output — the fixture is the
# committed artifact; the in-crate .cdx.json files are CI-only.
rm -f "$emitted"

printf 'wrote %s (from cargo-cyclonedx %s against %s)\n' \
    "$fixture_dir/valid.json" "$pinned_version" "$target_crate"
